### ISSUE TITLE
Running Ecdar on MacOS

### ISSUE THREAD

**Issue by magoorden** [Ecdar/Ecdar-GUI#100]
In this issue I document what I do to run Ecdar on my MacOS and briefly state what is working and what not. We need to make proper separate issues on specific parts that can be picked up in a single merge request.

As mentioned in #75, running Ecdar inside a virtual machine on MacOS is not working due to performance issues.

Currently I need to use a Java manager to force MacOS to use the correct Java version to launche Ecdar (all 'normal' options do not work). For this I use [SDKMAN!](https://sdkman.io/). Once you have installed the tool, you need to install the right Java version. Currently that is `java 11-zulu`. So you do this with
```bash
sdk install java 11-zulu
```

Now, each time you want to start Ecdar, you need to tell your terminal to use the right Java version. This is done with
```bash
sdk use java 11-zulu
```
Then you just launch Ecdar using the `ecdar` bash script in Ecdar's `bin` folder
```
./ecdar
```

This will launch a workable (but not perfect) GUI in which you can do modeling of your system. Queries cannot be run, as the GUI cannot make a connection with the engines. Maybe (?) MacOS is blocking the ports used for the communication between the GUI and the engines.

**Comment by magoorden** [comment]
This is a web page from Apple on how to deploy Java applications for MacOS: https://developer.apple.com/library/archive/documentation/Java/Conceptual/Java14Development/03-JavaDeployment/JavaDeployment.html#//apple_ref/doc/uid/TP40001885-SW1.

**Comment by Nielswps** [comment]
Using the new `runtimeZip` Gradle task now allows for Linux, Windows, and MacOS (both Intel- and ARM-based) versions. However, the engines are currently not available for either MacOS. 
j-Ecdar will be compatible with `native-image`, which I'm currently working on, and the SW5 version of Reveaal allegedly has a MacOS target setup with cargo. which will be available when simulation is merged in.
