### ISSUE TITLE
Scaling is not accurate when opening ecdar. 

### ISSUE THREAD

**Issue by WassawRoki** [Ecdar/Ecdar-GUI#112]
Description:  Scaling is not accurate when opening ecdar. Some parts are messing at the edges of the window.

Screenshot: 
![image](https://user-images.githubusercontent.com/56611129/207822014-653398f4-86e4-4a2c-bfbe-fc4f65f9a0c8.png)

Potential solution:
Right now, it can be fixed by changing the scaling under the view option in the toolbar, e.g change it to 1.25x and back to 1.0x. Which indicates that which ever function is used when re scaling, could fix the initial scaling.

**Comment by Nielswps** [comment]
I am unable to recreate this issue on the main branch. It is related to the issue reported in #88 and might have been resolved during some changes made to the way the side panes are opened and closed.

Please reopen, if the issue reappears
