### ISSUE TITLE
Some backend stubs are being lost and never closed on exit

### ISSUE THREAD

**Issue by seblund** [Ecdar/Ecdar-GUI#134]
When running the GUI, often many engine processes are left running when the application closes. When debugging through the `closeAllBackends` calls you notice that the `BackendDriver.openBackendConnections` and `QueryHandler.connections` do not have as many `BackendConnection`s as the GUI has started (it should be the same as they are only ever closed on exit or backend change). 

This is clear if you explicitly keep a list of all `BackendConnection`s started in `BackendDriver.tryStartNewBackendConnection`, and close them at exit, no processes are left hanging and all is good. While this may be an easy fix, it doesn't solve the underlying issue of `BackendConnection`s disappearing. If they disappear we can't reuse them. 

I can't really figure out where in the code the `BackendConnection`s are lost since the connections move around a lot, but i haven't done a lot of debugging. 

How to reproduce:
- Either add a debug variable in `BackendDriver.tryStartNewBackendConnection` or use Task Manager to count the number of started processes/connections.
- Add a breakpoint in `setOnCloseRequest`
- Run the gui with a debugger attached.
- Open the university example
- Click the run all queries button to start a bunch of connections.
- Close the GUI
- Use debugger to check the number of processes/connections `backendDriver` and `queryHandler` have compared to the actual number of processes.

**Comment by Nielswps** [comment]
This issue was also encountered during the SW5 multi-project, however, the issue never seems to occur on my machine:laughing: I will take a look at it first thing next week.
I think you are right, that the underlying issue that should be fixed is the disappearance of the connections.
