### ISSUE TITLE
Query types renaming

### ISSUE THREAD

**Issue by seblund** [Ecdar/Ecdar-GUI#138]
So this is what the current list of query types looks like in the GUI:
![image](https://user-images.githubusercontent.com/17483094/221211820-76a94d7c-82cb-4041-9565-1838d6b82ad4.png)
From today's meeting, the only changes are 
- `global-consistency [GCon]` should be renamed to `local-consistency [LCon]` 
- `consistency [lCon]` should be renamed to `consistency [Con]`

Other than that:
- `quotient [\]` is not a query type and should be removed from the list

The engines do not currently support `local-consistency:` (for `local-consistency [LCon]`) in their grammar but they should in the future.

We should probably also be consistent with the capitalizations in the shorthands. So either `[Spec], [Impl], [Con], [LCon], [Bsim], [Get]` or `[spec], [impl], [con], [lCon], [bsim], [get]`. I prefer the first.

**Comment by Nielswps** [comment]
Should we rename `bisim` to `bi-simulation`? And should `[Bsim]` be `[BSim]`?

**Comment by seblund** [comment]
> Should we rename `bisim` to `bi-simulation`?
`bisim` is short for bisimulation minimization so I don't think `bi-simulation` makes sense. But it should probably be `bisim-minim` as it is specified in the grammar here https://github.com/Ecdar/j-Ecdar/issues/2

> And should `[Bsim]` be `[BSim]`?
I'm fine with either. In the other cases e.g. `local-consistency -> LCon` we capitalize `L` and `C` because it is two words. But "bsim" is just short for bisimulation which is one word, so it could be either 🤷‍♂️
