### ISSUE TITLE
Drop down for possible operations

### ISSUE THREAD

**Issue by ulriknyman** [Ecdar/Ecdar-GUI#14]
Have a drop down next to the query with all the possible operations.

The name to the left is the text string that is send to the verification engine.
The thing to the right is the symbol

refinement: ≤ ref
quotient: \\ quo
specification: Spec
implementation: Imp
local-consistency: l-Con  (Check which consistency) 
global-consistency: g-Con
bisim-min: bsim
get-new-component: get

**Comment by Nielswps** [comment]
![Query Dropdown Illustration](https://user-images.githubusercontent.com/42961494/108503240-545d1c00-72b4-11eb-8802-8623eed062d6.jpg)
