### ISSUE TITLE
Zoom to fit does not always fit entire component

### ISSUE THREAD

**Issue by seblund** [Ecdar/Ecdar-GUI#44]
This is mainly an issue in pr #13 where a large part of the component is not in view:
![hDYAQrC](https://user-images.githubusercontent.com/17483094/161544500-840edcc0-5697-49ce-b005-30b5aad1d577.gif)

In the `main` branch there is missing padding at the bottom of tall components:
![TN3NX0M](https://user-images.githubusercontent.com/17483094/161543605-49289bdf-40c7-4451-80e9-f1fdef4b8b2f.gif)

**Comment by Nielswps** [comment]
Will be closed by merging #39
