### ISSUE TITLE
Missing zoom out icon

### ISSUE THREAD

**Issue by ulriknyman** [Ecdar/Ecdar-GUI#62]
The icon for Zooming out is replaced by the letter "J". 

![image](https://user-images.githubusercontent.com/12754059/173183791-4e72f45d-8f80-4e46-a810-88215e04d171.png)

This bug was observed on version 2.3.0-beta running on Ubuntu 20.04.4 LTS.

**Comment by Nielswps** [comment]
PR #79 might resolve this issue. We should probably find time during August to pull the related branch and test the fix on a machine that is having the issue

**Comment by Nielswps** [comment]
PR #79 seems to have solved the issue, I have tried to replace the dependency on GoogleMaterialDesignIcons with the already used MaterialIcon, however, we have to test whether the manually added font file could be removed
