### ISSUE TITLE
Preserve whitespace for queries

### ISSUE THREAD

**Issue by Nielswps** [Ecdar/Ecdar-GUI#85]
Whitespace should not be stripped from queries, as this can cause issues for the backends

**Comment by Hammad-qadeer** [comment]
Hello @Nielswps how can I reproduce the issue?

**Comment by Nielswps** [comment]
The issue is related to the upcoming "saveAs" functionality related to component generation. I have already implemented a fix, I just needed to run it by the Reveaal team
